source 'https://rubygems.org'
gem 'rake'
# gem 'activerecord'
# gem 'pg'
gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'database_cleaner'
gem 'rspec'
gem 'rspec-sinatra'
gem 'capybara'
# gem 'rspec'
# gem 'faker'
